---
apiVersion: batch/v1
kind: Job
metadata:
  name: habana-ai-smi
spec:
  template:
    spec:
      containers:
        - name: habana-ai-smi
          image: ghcr.io/fabiendupont/habana-ai-smi:1.6.0-439
          imagePullPolicy: Always
          command:
            - "sleep"
            - "infinity"
          resources:
            limits:
              habana.ai/gaudi: 8
          securityContext:
            capabilities:
              add:
                - "SYS_RAWIO"
      restartPolicy: Never
  backoffLimit: 1
